### ISSUE TITLE
Identify where the content of datatogether.org is loading from

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/datatogether#1]
@lgierth where is the content of datatogether.org loading from?  It doesn't match the content of this repo. (I need to add some links)

**Comment by ghost** [comment]
The current content is simply something I put up quickly while watching your code4lib presentation. Since then we've done nothing about it so that's the current state.

There's no website-ish content here either?

**Comment by flyingzumwalt** [comment]
that's fine. I just wanted to add a link to my slides at https://github.com/ipfs/datatogether/tree/master/presentations

I won't be putting work into this website for a while, unless some other people (ie. @b5) want to make it into a thing sooner rather than later.

**Comment by ghost** [comment]
Taken care of in #2
